### ISSUE TITLE
Deadlock when processing specific documents.

### ISSUE THREAD

**Issue by glasen** [klehmann/domino-jna#41] opened 2020-02-04 11:39 UTC
I run in some strange bug yesterday:

When processing a big NSF-file (~30GB), my program hangs when it tries to get the item "$MessageID" using the method "getItemValueString". This happens when the Form-Type is a "Notice" or an "Appointment". After implementing a workaround my programm can process the whole file with about 100k documents.

**Comment by glasen** [comment] 2020-02-05 09:33
The problem also occured when reading a "Reply"-form. I narrowed the deadlock down to the method "fromLMBCS(byte[] data)":

"data" gets filled with a single random byte. When using the debugger in IntelliJ and jumping in your code the deadlock does not occur.

**Comment by klehmann** [comment] 2020-02-05 09:44
Weird. A stacktrace of that deadlock would be interesting. Don't see anything in that method that looks suspicious.

**Comment by klehmann** [comment] 2020-02-05 10:22
Ok, I can confirm that OSTranslate32 does not like to be called with a byte array value of [1], probably because it's one of the LMBCS group codes (http://www.docjar.com/html/api/com/ibm/icu/charset/CharsetLMBCS.java.html) and more data is expected. It just runs forever.

Searching for a workaround.

**Comment by glasen** [comment] 2020-02-05 10:34
Yes, i'm using the latest version.

**Comment by klehmann** [comment] 2020-02-05 10:46
Ok, not true. The bug is in the fromData method. Should hopefully be fixed with 12064acae0a3dce045b17d1f66f19b9baf15539e.
Will publish a new version this week.

**Comment by glasen** [comment] 2020-02-05 12:14
I checked both files and the byte values are "1" for the "broken" Items.

**Comment by glasen** [comment] 2020-02-05 13:04
I've compiled "domino-jna" from master and your bugfix seems to work. The deadlock is gone for both NSF-files.

**Comment by klehmann** [comment] 2020-02-05 13:23
Great! Thanks for testing!

**Closed by klehmann** 2020-02-05 13:23 UTC
